language: java

jdk:
  - oraclejdk8

python:
  - 3.7

jobs:
  include:
    - name: Build
      script: ./build
    - name: Style Check
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle checkstyleMain checkstyleTest
    - name: Custom Tests
      script: ./test
    - name: MJTest Shared Lexer Tests
      script:
        - ./build
        - git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest.git
        - MJ_RUN="./run" ./mjtest/mjt.py lexer --ci_testing --parallel
