language: java

env:
  global:
    - MJ_RUN="./run"
    - MJ_TIMEOUT=60
    - MJ_BIG_TIMEOUT=0
    - SWIFT_VERSION="4.2" # Version to install with swiftenv
    - TERM="dumb" # Remove interactive status updates in Gradle output

matrix:
  include:
    - os: linux
      name: "Checkstyle"
      # sudo: required
      # dist: trusty
      jdk: oraclejdk8
      env: TESTTYPE=checkstyle
    - os: linux
      name: "Frontend and Firm Tests"
      # sudo: required
      # dist: trusty
      jdk: oraclejdk8
      env: TESTTYPE=frontend
    - os: linux
      name: "Compilation Tests with Own Backend"
      # sudo: required
      # dist: trusty
      jdk: oraclejdk8
      env: TESTTYPE=backend
    - os: osx
      name: "Frontend and Firm Tests"
      osx_image: xcode10.1
      env: TESTTYPE=frontend
    - os: osx
      name: "Compilation Tests with Own Backend"
      osx_image: xcode10.1
      env: TESTTYPE=backend

install:
  - source ~/virtualenv/python3.6/bin/activate
  - python3 --version
  - |
    case "$TESTTYPE" in
      checkstyle) ;;
      frontend) ;;
      backend)
        # Due to the time required to run the Swift installation, the install script
        # should only be present in jobs that actually need Swift installed.
        if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then \
          eval "$(curl -sL https://swiftenv.fuller.li/install.sh)" ;
        fi ;;
      *)
        echo "Unknown test type! Quitting ..."; return 1 ;;
    esac

script: |
    case "$TESTTYPE" in
      checkstyle)
        ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle checkstyleMain checkstyleTest
        ;;
      frontend)
        ./build --no-swift && \
        echo "" && echo "" && echo "#### LEXER TESTS" && \
        ./mjtest/mjt.py lexer --ci_testing --parallel && \
        echo "" && echo "" && echo "#### PARSER TESTS" && \
        ./mjtest/mjt.py syntax --ci_testing --parallel && \
        echo "" && echo "" && echo "#### AST GENERATION TESTS" && \
        ./mjtest/mjt.py ast --ci_testing --parallel && \
        echo "" && echo "" && echo "#### SEMANTIC TESTS" && \
        ./mjtest/mjt.py semantic --ci_testing --parallel && \
        echo "" && echo "" && echo "#### FIRM COMPILATION TESTS" && \
        ./mjtest/mjt.py compile-firm --ci_testing --parallel
        ;;
      backend)
        ./build && \
        echo "" && echo "" && echo "#### COMPILATION TESTS" &&
        ./mjtest/mjt.py compile --ci_testing --parallel && \
        echo "" && echo "" && echo "#### COMPILATION TESTS (BIG TEST CASES)" &&
        ./molki__build_run_check-BigTests.py &&
        echo "" && echo "" && echo "#### COMPILATION TESTS (NO OPTIMIZATIONS)" &&
        ./mjtest/mjt.py no-optimization --ci_testing --parallel
        ;;
      *)
        echo "Unknown test type! Quitting ..."; return 1
        ;;
    esac
