#os:
#  - linux
#  - osx

language: java

matrix:
  include:
    - os: linux
      name: "Frontend and Firm Compilation Tests"
      sudo: required
      dist: trusty
      jdk: oraclejdk8
      env: TESTTYPE=frontend
    - os: linux
      name: "Compilation Tests with Custom Backend"
      sudo: required
      dist: trusty
      jdk: oraclejdk8
      env: TESTTYPE=backend
    - os: osx
      name: "Frontend and Firm Tests"
      osx_image: xcode10.1
      env: TESTTYPE=frontend
    - os: osx
      name: "Compilation Tests with Custom Backend"
      osx_image: xcode10.1
      env: TESTTYPE=backend

# Due to the time required to run the Swift installation, the install script
# > eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
# should only be present in jobs that actually need Swift installed.

      # before_script:
  #  - source ~/virtualenv/python3.6/bin/activate

env:
  global:
    - MJ_RUN="./run"
    - MJ_TIMEOUT=60
    - MJ_BIG_TIMEOUT=0
    - TERM='dumb' # Remove interactive status updates in Gradle output
    - SWIFT_VERSION="4.2" # Version to install with swiftenv

      #install:
      #- case "$TESTTYPE" in
      #frontend)
      #  ;;
      #backend)
      #  eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      #  ;;
      #*)
      #  echo "Unknown test type: $TESTTYPE! Quitting ..." ;
      #  return 1;
      #  ;;
      #esac

script:
  - case "$TESTTYPE" in
      frontend)
        ./build --no-swift && \
        ./mjtest/mjt.py lexer --ci_testing --parallel && \
        ./mjtest/mjt.py syntax --ci_testing --parallel && \
        ./mjtest/mjt.py ast --ci_testing --parallel && \
        ./mjtest/mjt.py semantic --ci_testing --parallel && \
        ./mjtest/mjt.py compile-firm --ci_testing --parallel ;
        ;;
      backend)
        ./build && \
        echo "#### Compilation Tests" &&
        ./mjtest/mjt.py compile --ci_testing --parallel && \
        echo "#### Compilation Tests for Big Tests" &&
        ./molki__build_run_check-BigTests.py &&
        echo "#### Compilation Tests without Optimizations" &&
        ./mjtest/mjt.py no-optimization --ci_testing --parallel ;
        ;;
      *)
        echo "Unknown test type: $TESTTYPE! Quitting ..." ;
        return 1;
        ;;
    esac


    #jobs:
    #include:
    #- stage: build
    #  name: Build
    #  install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    #  script: ./build
    #- stage: test
    #  name: Style Check
    #  script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle checkstyleMain checkstyleTest
      #- name: Lexer Tests
      #script: ./build --no-swift && ./mjtest/mjt.py lexer --ci_testing --parallel
      #- name: Parser Tests
      #script: ./build --no-swift && ./mjtest/mjt.py syntax --ci_testing --parallel
      #- name: AST Tests
      #script: ./build --no-swift && ./mjtest/mjt.py ast --ci_testing --parallel
      #- name: Semantic Tests
      # script: ./build --no-swift && ./mjtest/mjt.py semantic --ci_testing --parallel
      #- name: Firm Compilation Tests
      #script: ./build --no-swift && ./mjtest/mjt.py compile-firm --ci_testing --parallel
      #- name: Compilation Tests
      #install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      #script: ./build && ./mjtest/mjt.py compile --ci_testing --parallel
      #- name: No Optimization Tests
      #install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      #script: ./build && ./mjtest/mjt.py no-optimization --ci_testing --parallel
      #- name: MJ Compilation Tests
      #install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      #script: ./build && ./molki__build_run_check.py
      #- name: Big Tests
      #install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      #script: ./build && ./molki__build_run_check-BigTests.py
