language: java

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: build
      name: Build
      script: ./build
    - name: Stylecheck
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle checkstyleMain checkstyleTest
    - stage: test
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle test
