language: java

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: build
      name: Build
      script: ./build
    - stage: test
      name: Shared mjtest Lexer Tests
      script:
        - source ~/virtualenv/python3.6/bin/activate
        - ./build
        - git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest.git
        - MJ_RUN="./run" ./mjtest/mjt.py lexer --ci_testing --parallel
    - name: Custom mjtest Lexer Tests
      script:
        - source ~/virtualenv/python3.6/bin/activate
        - ./build
        - git clone --recursive https://git.scc.kit.edu/ubduq/mjtest.git
        - MJ_RUN="./run" ./mjtest/mjt.py lexer --ci_testing --parallel
    - name: Style Check
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle checkstyleMain checkstyleTest
