language: java

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: check
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle check
    - stage: build
      script: ./build
    - stage: test
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle test
