language: java

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: stylecheck
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle checkstyleMain checkstyleTest
    - stage: build
      script: ./build
    - stage: test
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle test
