language: java

env:
  global:
    - MJ_RUN="./run"        # Compiler run script used by mjtest
    - MJ_TIMEOUT=60         # Timeout for normal test cases
    - MJ_BIG_TIMEOUT=0      # Timeout for test cases marked as big
    - SWIFT_VERSION="4.2"   # Version to install with swiftenv
    - TERM="dumb"           # Remove interactive status updates in Gradle output

matrix:
  include:
    - os: linux
      name: "Checkstyle"
      jdk: oraclejdk8
      env: TESTTYPE=checkstyle
    - os: linux
      name: "Frontend and Firm Tests"
      jdk: oraclejdk8
      env: TESTTYPE=frontend
    - os: linux
      name: "Compilation Tests with Own Backend"
      jdk: oraclejdk8
      env: TESTTYPE=backend
    - os: osx
      name: "Frontend and Firm Tests"
      osx_image: xcode10.1
      env: TESTTYPE=frontend
    - os: osx
      name: "Compilation Tests with Own Backend"
      osx_image: xcode10.1
      env: TESTTYPE=backend

install:
  - python3 --version
  - source ~/virtualenv/python3.6/bin/activate
  - python3 --version
  - |
    if [ "$TESTTYPE" = "backend" ] && [ "$TRAVIS_OS_NAME" -ne "osx" ]; then
      eval "$(curl -sL https://swiftenv.fuller.li/install.sh)" ;
    fi

script:
  - ./scripts/travis-test.sh
