language: java

jdk:
  - oraclejdk8

jobs:
  include:
    - name: Build
      script: ./build
    - name: Style Check
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle checkstyleMain checkstyleTest
    - name: Tests
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle test
