language: java
sudo: required
dist: trusty

jdk:
  - oraclejdk8

# Due to the time required to run the Swift installation, the install script
# > eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
# should only be present in jobs that actually need Swift installed.

before_script:
  - source ~/virtualenv/python3.6/bin/activate

env:
  - MJ_RUN="./run" MJ_TIMEOUT=60 SWIFT_VERSION="4.2"

jobs:
  include:
    - stage: build
      name: Build
      script: ./build
    - stage: test
      name: Swift Test
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swiftc -o swift.out test.swift
        - ./swift.out
