language: java

jdk:
  - oraclejdk8

before_script:
  - source ~/virtualenv/python3.6/bin/activate

env:
  - MJ_RUN="./run" MJ_TIMEOUT=60

jobs:
  allow_failures:
    - name: Shared mjtest Lexer Tests
    - name: Shared mjtest Syntax Tests

  include:
    - stage: build
      name: Build
      script: ./build
    - stage: test
      name: Shared mjtest Lexer Tests
      script:
        - ./build
        - git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest.git
        - cd mjtest/tests
        - git checkout master
        - cd ../..
        - ./mjtest/mjt.py lexer --ci_testing --parallel
    - stage: test
      name: Shared mjtest Syntax Tests
      script:
        - ./build
        - git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest.git
        - cd mjtest/tests
        - git checkout master
        - cd ../..
        - ./mjtest/mjt.py parser --ci_testing --parallel
    - name: Custom mjtest Tests (Lexer + Syntax)
      script:
        - ./build
        - git clone --recursive https://git.scc.kit.edu/ubduq/mjtest.git
        - cd mjtest/tests
        - git checkout dev
        - cd ../..
        - ./mjtest/mjt.py lexer --ci_testing --parallel
        - ./mjtest/mjt.py syntax --ci_testing --parallel
    - name: Style Check
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle checkstyleMain checkstyleTest
