language: java

jdk:
  - oraclejdk8

before_script:
  - source ~/virtualenv/python3.6/bin/activate

env:
  - MJ_RUN="./run" MJ_TIMEOUT=60

jobs:
  allow_failures:
    - name: Firm Compilation Tests

  include:
    - stage: build
      name: Build
      script: ./build
    - stage: test
      name: Style Check
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle checkstyleMain checkstyleTest
    - name: Lexer Tests
      script: ./build && ./mjtest/mjt.py lexer --ci_testing --parallel
    - name: Parser Tests
      script: ./build && ./mjtest/mjt.py syntax --ci_testing --parallel
    - name: AST Tests
      script: ./build && ./mjtest/mjt.py ast --ci_testing --parallel
    - name: Semantic Tests
      script: ./build && ./mjtest/mjt.py semantic --ci_testing --parallel
    - name: Firm Compilation Tests
      script: ./build && ./mjtest/mjt.py compile-firm --ci_testing --parallel
