language: java

jdk:
  - oraclejdk8

before_script:
  - source ~/virtualenv/python3.6/bin/activate

env:
  - MJ_RUN="./run" MJ_TIMEOUT=60

jobs:
  allow_failures:
    - name: Shared mjtest Tests

  include:
    - stage: build
      name: Build
      script: ./build
    - stage: test
      name: Lexer Tests
      script:
        - ./build
        # - git clone --recursive https://git.scc.kit.edu/ubduq/mjtest.git
        # - cd mjtest/tests
        # - git checkout dev
        # - cd ../..
        - ./mjtest/mjt.py lexer --ci_testing --parallel --output_no_incorrect_reports
    - name: Style Check
      script: ./mini-java-compiler/gradlew -b ./mini-java-compiler/build.gradle checkstyleMain checkstyleTest
