#!/bin/bash

SCRIPT_PATH=$(dirname "$0")

$SCRIPT_PATH/build > /dev/null || exit 1

TMP_FILE=`mktemp`
TIMEFORMAT=$'\nDuration: %R seconds'
time ( $SCRIPT_PATH/run "$@"; echo $? > $TMP_FILE )
EXIT_CODE=`cat $TMP_FILE`
rm $TMP_FILE

echo "Exit Code: $EXIT_CODE"
