#!/bin/bash

SCRIPT_PATH=$(dirname "$0")
export LD_LIBRARY_PATH="$SCRIPT_PATH/mini-java-compiler/lib"
java -jar -ea "$SCRIPT_PATH/mini-java-compiler/build/libs/mini-java-compiler-1.0-SNAPSHOT.jar" "$@"
