package edu.kit.minijava.lexer;

public enum TokenType {

    // MARK: - Keywords

    ABSTRACT, ASSERT, BOOLEAN, BREAK, BYTE, CASE, CATCH, CHAR, CLASS, CONST, CONTINUE, DEFAULT, DOUBLE, DO, ELSE, ENUM,
    EXTENDS, FALSE, FINALLY, FINAL, FLOAT, FOR, GOTO, IF, IMPLEMENTS, IMPORT, INSTANCEOF, INTERFACE, INT, LONG, NATIVE,
    NEW, NULL, PACKAGE, PRIVATE, PROTECTED, PUBLIC, RETURN, SHORT, STATIC, STRICTFP, SUPER, SWITCH, SYNCHRONIZED, THIS,
    THROWS, THROW, TRANSIENT, TRUE, TRY, VOID, VOLATILE, WHILE,

    // MARK: - Operators

    ASSIGN, EQUALS, NOT_EQUALS, LESS_THAN, LESS_THAN_OR_EQUAL, GREATER_THAN, GREATER_THAN_OR_EQUAL,

    ADD, ADD_AND_ASSIGN, SUBTRACT, SUBTRACT_AND_ASSIGN, MULTIPLY, MULTIPLY_AND_ASSIGN, DIVIDE, DIVIDE_AND_ASSIGN,
    MODULO, MODULO_AND_ASSIGN, INCREASE, DECREASE,

    LOGICAL_NEGATION, LOGICAL_OR, LOGICAL_AND, QUESTION_MARK, COLON,

    BITWISE_NOT, BITWISE_AND, BITWISE_AND_AND_ASSIGN, BITWISE_OR, BITWISE_OR_AND_ASSIGN, BITWISE_XOR,
    BITWISE_XOR_AND_ASSIGN, SHIFT_LEFT, SHIFT_LEFT_AND_ASSIGN, SHIFT_RIGHT, SHIFT_RIGHT_AND_ASSIGN,
    UNSIGNED_SHIFT_RIGHT, UNSIGNED_SHIFT_RIGHT_AND_ASSIGN,

    // MARK: - Separators

    OPENING_PARENTHESIS, CLOSING_PARENTHESIS, OPENING_BRACE, CLOSING_BRACE, OPENING_BRACKET, CLOSING_BRACKET, SEMICOLON,
    COMMA, PERIOD,

    // MARK: - OTHER

    IDENTIFIER, // [A-ZA-Z_][A-ZA-Z0-9_]*
    INTEGER_LITERAL, // 0 | [1-9][0-9]*
}
